# @format
title: OTLC
description: Welcome to our CUhackit project!
baseurl: "" # leave blank if it's a root directory, or set to your subfolder if applicable
url: "http://localhost:4000" # live URL for your site
theme: jekyll-theme-merlot
