# @format

title: "OLTC"
description: "OLTC website hosted on GitHub Pages"
url: "https://NevahLucky.github.io"
#theme: "jekyll-theme-merlot"
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme 